### ISSUE TITLE
cmd + , opens preferences of tuneful even if different app is focused

### ISSUE THREAD

**Issue by scsskid** [martinfekete10/Tuneful#159]
version 2.0.1

cmd + , opens preferences of tuneful even diffrent app is focused

seems tuneful sets if as a shortcut system wide

**Comment by martinfekete10** [comment]
Thanks for reporting, this will be fixed in the next release

**Comment by blckwltz** [comment]
I don't know if it's intentional behaviour, but seems like the connected problem. Before the popover was closed when focusing different app, now it stays open in this case.

**Comment by martinfekete10** [comment]
This is now fixed in the newest release

**Comment by blckwltz** [comment]
I've tested the latest version and now `cmd + ,` is just ignored in other apps when Tuneful is running. Also popover is still not closed on the outside click.

**Comment by martinfekete10** [comment]
Shoot I don't know how I missed this, will revert it ASAP.

There's a issue for popover not closing on outside click already that is still open. It actually closes on outside click, but only if you interact with it first (e.g. click on play/pause); still haven't figured out the root cause tho

**Comment by martinfekete10** [comment]
Fixed now in the newest udpate, should trigger Tuneful settings only when active
