### ISSUE TITLE
Notch player stays open when dragging mouse trough notch to other screen

### ISSUE THREAD

**Issue by CasperVerswijvelt** [martinfekete10/Tuneful#182]
**Issue:**
When dragging trough the notch to the external screen above, the notch player sometimes stays open, depending on how fast you are moving the mouse.
https://github.com/user-attachments/assets/9accb178-5cdc-4876-b63e-2bf08b72bb05

**Screen arrangement:**
<img width="381" alt="Image" src="https://github.com/user-attachments/assets/09a17db8-f1dd-4ec4-b1ca-cdef6ff8c405" />

**Tuneful settings;**
![Image](https://github.com/user-attachments/assets/1279fa70-f727-4433-8656-86b12ab36684)

**Comment by martinfekete10** [comment]
Good catch, thanks! Will be fixed in the next release

**Comment by martinfekete10** [comment]
This should be fixed in v.2.5.0 which is already available in App Store. Let me know if you encounter anything else!

**Comment by CasperVerswijvelt** [comment]
Just updated to 2.5.0, and I can still reproduce the issue like before

Added a new video that is a bit clearer in describing the issue than my initial report:

https://github.com/user-attachments/assets/fa0cbb20-783d-4510-bad9-ab10e3554ecf

**Comment by martinfekete10** [comment]
Hmm, I don't think there is a way to fix this other than setting mouse hover duration to be higher than 0. Otherwise, Tuneful can't differentiate between intentional and non-intentional hover

**Comment by CasperVerswijvelt** [comment]
I understand that, and I don't mind it swiftly animating when I hover over it, but the issue is that it stays open even when my mouse is no longer hovering over the notch (video from previous message, 00:06)

**Comment by martinfekete10** [comment]
Ahh sorry misunderstood you. You're correct, I'll investigate it

**Comment by CasperVerswijvelt** [comment]
Any update on this / can we reopen the issue?

**Comment by martinfekete10** [comment]
I did multiple enhacements to the hover logic and can no longer reproduce this. Are you still encountering this on your end in v2.6.2?

**Comment by CasperVerswijvelt** [comment]
Yeah seems to be fixed in latest version, app wasn't updated automatically. My bad.
